PolSourceTasks/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cover__c</fullName>
        <label>Cover</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Soft</fullName>
                </value>
                <value>
                    <fullName>Hard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publisher</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <displayFormat>BK-{00000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PolSourceTasks/src/objects/Edition__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Editions</relationshipLabel>
        <relationshipName>Editions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cover__c</fullName>
        <label>Cover</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Soft</fullName>
                </value>
                <value>
                    <fullName>Hard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PolSourceTasks/src/classes/BookService.cls
@RestResource(urlMapping='/Book/*')
global with sharing class BookService {

    @HttpGet
    global static ItemWrapper getBookByISBN() {
        RestRequest request = RestContext.request;
        String bookISBN = request.requestURI.substring(request.requestURI.lastIndexOf('Book/')+5);
        if(!bookISBN.isNumeric()){
            throw new MyException('ISBN must contain only from digits!');
        }
        Decimal bookISBNdec = Decimal.valueOf(bookISBN);      
        Book__c book = [SELECT Title__c, Author__c, Id, Name FROM Book__c WHERE ISBN__c = :bookISBNdec]; 
        List<Edition__c> editions = [SELECT Name, Price__c, Cover__c, Release_Date__c, Id FROM Edition__c WHERE Book__c = :book.Id]; 
        ItemWrapper wrapper = new ItemWrapper();
        wrapper.name = book.Name;
        wrapper.title = book.Title__c;
        wrapper.author = book.Author__c;
        wrapper.id = book.Id;
        for(Integer i = 0; i < editions.size(); i++) {
            ListWrapper lwrapper = new ListWrapper();
            lwrapper.name = editions.get(i).Name;
            lwrapper.price = editions.get(i).Price__c;
            lwrapper.cover = editions.get(i).Cover__c;
            lwrapper.releaseDate = editions.get(i).Release_Date__c;
            lwrapper.id = editions.get(i).Id;
            wrapper.editions.add(lwrapper);
        }        
        return wrapper;
    }
    
    @HttpPost
    global static Id createBook(String title, String author, String isbn, Id publisher, String cover, Decimal price, String name, Date releaseDate, Boolean active) {
        Book__c book = new Book__c();
        Edition__c edition = new Edition__c();
        book.Publisher__c = publisher;
        book.Title__c = title;
        book.Author__c = author;
        book.ISBN__c = Decimal.valueOf(isbn);
        insert book;
        if(cover != null && price != null){
        	edition.Book__c = book.Id;
        	edition.Cover__c = cover;
        	edition.Price__c = price;
        	edition.Name = name;
            edition.Release_Date__c = releaseDate;
            edition.Active__c = active;
            insert edition;
        }
        return book.Id;
    }
    
    @HttpDelete
    global static String deleteBook() {
        RestRequest request = RestContext.request;
        String bookID = request.requestURI.substring(request.requestURI.lastIndexOf('Book/')+5);
        Book__c book = [SELECT Id FROM Book__c WHERE Id = :bookID];
        delete book;
        return 'Record deleted';
    }    
}