PolSourceTasks/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Cover__c</fullName>
        <label>Cover</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Soft</fullName>
                </value>
                <value>
                    <fullName>Hard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Book</label>
    <nameField>
        <displayFormat>BK-{00000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PolSourceTasks/src/objects/Edition__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Editions</relationshipLabel>
        <relationshipName>Editions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cover__c</fullName>
        <label>Cover</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Soft</fullName>
                </value>
                <value>
                    <fullName>Hard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PolSourceTasks/src/classes/EditionTriggerTest.cls
@isTest
private class EditionTriggerTest {
    
    @isTest
    static void editionInsertNoActiveTest(){
        //given
        Book__c book = new Book__c();
		book = TestDataFactory.prepareBook();        
    	List<Edition__c> editions = new List<Edition__c>();
    	//when
    	for(Integer i = 0; i<3; i++){
    		editions.add(new Edition__c(Name = ('e'+i), Book__c = book.Id, Cover__c = 'Soft', Release_Date__c = date.today(), Active__c = false));    		
    	}
    	insert editions;       
        update book;
        
        //then
        book = [SELECT Id, Available_editions__c FROM Book__c WHERE Id =: book.Id];
        System.assertEquals(0, book.Available_editions__c);
    }
    
    @isTest
    static void editionInsertWithActiveTest(){
        //given
       	Book__c book = new Book__c();
		book = TestDataFactory.prepareBook();        
    	List<Edition__c> editions = new List<Edition__c>();
    	
        //when
        for(Integer i = 0; i<3; i++){
    		editions.add(new Edition__c(Name = ('e'+i), Book__c = book.Id, Cover__c = 'Soft', Release_Date__c = date.today(), Active__c = true));    		
    	}
    	insert editions;      
        
        //then
        book = [SELECT Id, Available_editions__c FROM Book__c WHERE Id =: book.Id];
        System.assertEquals(3, book.Available_editions__c);
    }
    
    @isTest
    static void editionUpdateAddActiveTest(){
        //given
        Book__c book = new Book__c();
		book = TestDataFactory.prepareBook();  
    	List<Edition__c> editions = new List<Edition__c>();
    	for(Integer i = 0; i<3; i++){
    		editions.add(new Edition__c(Name = ('e'+i), Book__c = book.Id, Cover__c = 'Soft', Release_Date__c = date.today(), Active__c = false));    		
    	}
    	insert editions;        
        
        //when
        for(Integer i = 0; i<3; i++){
        	editions.get(i).Active__c = true;
        }
        update editions;
        
        //then
        book = [SELECT Id, Available_editions__c FROM Book__c WHERE Id =: book.Id];
        System.assertEquals(3, book.Available_editions__c);       
    }
    
    @isTest
    static void editionUpdateRemoveActiveTest(){
        //given
        Book__c book = new Book__c();
		book = TestDataFactory.prepareBook();  
    	List<Edition__c> editions = new List<Edition__c>();
    	for(Integer i = 0; i<3; i++){
    		editions.add(new Edition__c(Name = ('e'+i), Book__c = book.Id, Cover__c = 'Soft', Release_Date__c = date.today(), Active__c = true));    		
    	}
    	insert editions;        
        
        //when
        for(Integer i = 0; i<3; i++){
        	editions.get(i).Active__c = false;
        }
        update editions;
        
        //then
        book = [SELECT Id, Available_editions__c FROM Book__c WHERE Id =: book.Id];
        System.assertEquals(0, book.Available_editions__c);   
    }
    
    @isTest
    static void editionDeleteTest(){
        //given
        Book__c book = new Book__c();
		book = TestDataFactory.prepareBook();
    	List<Edition__c> editions = new List<Edition__c>();
    	for(Integer i = 0; i<3; i++){
    		editions.add(new Edition__c(Name = ('e'+i), Book__c = book.Id, Cover__c = 'Soft', Release_Date__c = date.today(), Active__c = true));    		
    	}
    	insert editions;        

        //when
        book = [SELECT Id, Available_editions__c FROM Book__c WHERE Id =: book.Id];
        System.assertEquals(3, book.Available_editions__c);   
        List<Edition__c> toDelete = [SELECT Id FROM Edition__c WHERE Book__c =: book.Id];
        delete toDelete;
        
        //then
        book = [SELECT Id, Available_editions__c FROM Book__c WHERE Id =: book.Id];
        System.assertEquals(0, book.Available_editions__c);   
    }
}