PolSourceTasks/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>BK-{00000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PolSourceTasks/src/objects/Opinion__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Opinions</relationshipLabel>
        <relationshipName>Opinions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opinion</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>Opinion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opinions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PolSourceTasks/src/classes/AddOpinionController_Test.cls
@isTest
public with sharing class AddOpinionController_Test {

    @isTest
    static void testCreateRecord() {
        //given
        Book__c book = TestDataFactory.prepareBook(true);
        Contact reader = TestDataFactory.prepareContact(true);
        Opinion__c opinion = new Opinion__c();
        ApexPages.StandardController standardController = new ApexPages.StandardController(opinion);
        AddOpinionPageController controller = new AddOpinionPageController(standardController);

        //when
        Id testId = controller.createRecord(opinion, book, reader);

        //then
        System.assert(testId != null);

    }

}