PolSourceTasks/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>BK-{00000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PolSourceTasks/src/objects/Edition__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Editions</relationshipLabel>
        <relationshipName>Editions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PolSourceTasks/src/classes/BookService_Test.cls
@isTest
public class BookService_Test {

    @isTest
    static void testGetBookByCorrectISBN() {
        //given
        Book__c book = TestDataFactory.prepareBook(true);
        List<Edition__c> editions = TestDataFactory.prepareEditions(true, book, true, 3);
        RestRequest request = new RestRequest();
        request.requestURI = 'https://playful-goat-198379-dev-ed.my.salesforce.com/services/apexrest/Book/' + book.ISBN__c;
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        //when
        ItemWrapper testBook = BookService.getBookByISBN();
        
        //then
        System.assert(testBook != null);
        System.assertEquals(3, testBook.editions.size());
    }
    
    @isTest
    static void testGetBookByWrongISBN() {
        //given
        String exceptionMsg = null;
        RestRequest request = new RestRequest();
        request.requestURI = 'https://playful-goat-198379-dev-ed.my.salesforce.com/services/apexrest/Book/dasd';
        request.httpMethod = 'GET';
        RestContext.request = request;
        String expectedError = 'ISBN must contain only from digits!';
        
        //when
        try{
        	ItemWrapper test = BookService.getBookByISBN();
        }catch(Exception e){
            exceptionMsg = e.getMessage();
        }       
        
        //then
        System.assertEquals(exceptionMsg.contains(expectedError), true);
    }
    
    @isTest
    static void testISBNWithoutBook() {
        String exceptionMsg = null;
        RestRequest request = new RestRequest();
        request.requestURI = 'https://playful-goat-198379-dev-ed.my.salesforce.com/services/apexrest/Book/1';
        request.httpMethod = 'GET';
        RestContext.request = request;
        String expectedError = 'List has no rows';
        
        //when
        try{
        	ItemWrapper test = BookService.getBookByISBN();
        }catch(Exception e){
            exceptionMsg = e.getMessage();
        }       
        
        //then
        System.assertEquals(exceptionMsg.contains(expectedError), true);
    }
}