PolSourceTasks/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>BK-{00000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PolSourceTasks/src/objects/Edition__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Editions</relationshipLabel>
        <relationshipName>Editions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PolSourceTasks/src/classes/EditionTriggerHandler.cls
public with sharing class EditionTriggerHandler {
   
   public void onAfterUpdate(Map<Id, Edition__c> newMap, Map<Id, Edition__c> oldMap){
        Set<Id> bookIds = new Set<Id>();
        for(Edition__c e : newMap.values()){             
            if(e.Active__c != oldMap.get(e.Id).Active__c){
                bookIds.add(e.Book__c);
            }             
        }        
        updateBookAvailableEditions(bookIds);		
    }
    
    public void onAfterInsert(Map<Id, Edition__c> newMap) {
        Set<Id> bookIds = new Set<Id>();
        for(Edition__c e : newMap.values()){             
            if(e.Active__c == true){
                bookIds.add(e.Book__c);
            }                      
        }		
        updateBookAvailableEditions(bookIds);
    }
    
    public void onAfterDelete(Map<Id, Edition__c> oldMap) {
        Set<Id> bookIds = new Set<Id>();
        for(Edition__c e : oldMap.values()){             
            if(e.Active__c == true){
                bookIds.add(e.Book__c);
            }             
        }        
        updateBookAvailableEditions(bookIds);
    }
    
    private static void updateBookAvailableEditions(Set<Id> bookIds) {
        List<Book__c> books = [SELECT Id, Available_editions__c, (SELECT Id, Active__c FROM Editions__r WHERE Active__c = true) bookEditions FROM Book__c WHERE Id IN :bookIds];
        for(Book__c b : books){
			b.Available_editions__c = b.Editions__r.size();   
        }
        update books;
    }
}