PolSourceTasks/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>BK-{00000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PolSourceTasks/src/objects/Opinion__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Opinions</relationshipLabel>
        <relationshipName>Opinions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Your record type doesn&apos;t allow you to insert an opinion</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Reader</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opinions</relationshipLabel>
        <relationshipName>Opinions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Opinion</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>Opinion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opinions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PolSourceTasks/src/classes/AddOpinionPageController.cls
public with sharing class AddOpinionPageController {

    public Opinion__c opinion { get; set; }
    public Book__c book { get; set; }
    public Contact con { get; set; }
    public ApexPages.StandardController standardController;

    public AddOpinionPageController(ApexPages.StandardController controller) {
        this.opinion = new Opinion__c();
        this.book = new Book__c();
        this.con = new Contact();
        this.standardController = controller;
    }

    public PageReference save() {
        Id retId;
        try {
            retId = createRecord(opinion, book, con);
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
        return new PageReference('/' + retId);
    }

    @TestVisible private Id createRecord(Opinion__c op, Book__c bk, Contact cn) {
        List<Book__c> bookIds = [SELECT Id FROM Book__c WHERE ISBN__c = :bk.ISBN__c];
        List<Contact> contacts = [SELECT Id FROM Contact WHERE Email = :cn.Email];

        if (bk.ISBN__c < 0) {
            throw new MyException(ProjectUtils.NEGATIVE_ISBN);
        }
        if (bookIds.size() == 0) {
            throw new MyException(ProjectUtils.ERROR_NO_ROWS_ISBN);
        }
        if (contacts.size() == 0) {
            cn.LastName = ProjectUtils.NEW_CONTACT_NAME;
            insert cn;
        }
        op.Book__c = bookIds.get(0).Id;
        op.Contact__c = contacts.get(0).Id;
        insert op;
        return op.Id;
    }

}