PolSourceTasks/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>BK-{00000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PolSourceTasks/src/objects/Edition__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Editions</relationshipLabel>
        <relationshipName>Editions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Edition</label>
    <nameField>
        <label>Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PolSourceTasks/src/classes/BooksEditionsNumberHandler.cls
public with sharing class BooksEditionsNumberHandler {
    
    public void onBeforeInsertOrUpdate(Map<Id, Edition__c> newMap, Map<Id, Edition__c> oldMap){
    	
    	List<Edition__c> editions = new List<Edition__c>();
    	for(Edition__c edi : (List<Edition__c>) newMap.values()) {    		
    		Book__c book = [SELECT Id, Available_editions__c, (SELECT Id FROM Editions__r) FROM Book__c WHERE Id =: edi.Book__c];
    		Integer currNumOfEd = 
    		if(currNumOfEd < book.Available_editions__c) {
    			editions.add(edi);
    		}
    	}
    	upsert editions;
    }
}